[package]
name = "chalk"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.23"
pest = "2.1.3"
pest_derive = "2.1.0"
regex = "1.5.4"