[package]
name = "chalk"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
lalrpop = "0.19.6"

[dependencies]
structopt = "0.3.23"
lalrpop-util = "0.19.6"
regex = "1.5.4"